# Generated by Django 4.1.3 on 2022-11-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('manufactureId', models.AutoField(primary_key=True, serialize=False)),
                ('manufactureName', models.CharField(max_length=100)),
                ('manufactureYearFounded', models.DateField()),
                ('manufactureHeadquarters', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('modelId', models.AutoField(primary_key=True, serialize=False)),
                ('manufactureName', models.CharField(max_length=150)),
                ('modelName', models.CharField(max_length=200)),
            ],
        ),
    ]
